# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='images',
            field=models.ImageField(blank=True, upload_to='../static/food/images'),
        ),
    ]
